### ISSUE TITLE
manual

### ISSUE THREAD

**Issue by mvhulten** [ReneVolution/profanity-omemo-plugin#1]
A short usage manual (as an addition to README.md) would be great.

**Comment by ReneVolution** [comment]
Absolutely agree ... even better, i should add a hint in README.md that the plugin is still in development.
Sorry for the inconvenience.

**Comment by mvhulten** [comment]
Yes, thanks, that is also a good idea!  I'm looking forward to use OMEMO with profanity.

**Comment by ReneVolution** [comment]
Me too :) ... just added the disclaimer to the README. Feel free to star the repo to get updates immediately.
