### ISSUE TITLE
Failed to load plugin: prof_omemo_plugin.py

### ISSUE THREAD

**Issue by nwtti** [ReneVolution/profanity-omemo-plugin#10]
I can't load the plugin, but profanity doesn't give any information about why it fails (or I'm just to stupid to find it, lol).
I'm using Arch Linux and the latest version of profanity and the omemo plugin from Github (Profanity installed via profantiy-git from AUR) . A profanity.log with '--log=DEBUG' is attached, but doesn't give any information on why it fails. You can also see, that I am able to install other plugins (ascii.py in this log file) without problems. 

[profanity.log.txt](https://github.com/ReneVolution/profanity-omemo-plugin/files/723827/profanity.log.txt)
(here's a [paste](https://s.witti.su/Y4k/raw) if you don't wanna download that file)

**Comment by ReneVolution** [comment]
Could you post the output when running `python setup.py install` from the source directory?

**Comment by nwtti** [comment]
I hope it is normal that I have to run it as root, otherwise I'll get an permission error with .../protobuf-3.1.0.post1-py3.6.egg/EGG-INFO/namespace_packages.txt.

[setup.log.txt](https://github.com/ReneVolution/profanity-omemo-plugin/files/723944/setup.log.txt)

**Comment by ReneVolution** [comment]
Yes, that is probably because it has to compile some protobuf sthings.

Anyways, just seeing you use Python 3.6 and i have never tested with Python 3 yet.
Do you mind running `python setup.py test` from the source directory? Maybe the issue is originated there.

**Comment by nwtti** [comment]
Thats interesting, `setup.py test `gives some errors using python3 (most of them because of the missing brackets when using print, but still errors), but works just fine using python2.
But `/plugins python_version` in profanity tells me, that profanity will use Python 3.6. Is there a way to use python2 instead in profanity?

[setup_p2.txt](https://github.com/ReneVolution/profanity-omemo-plugin/files/724172/setup_p2.txt)
[setup_p3.txt](https://github.com/ReneVolution/profanity-omemo-plugin/files/724173/setup_p3.txt)

**Comment by ReneVolution** [comment]
Oh great .. thanks for the pointer. Will definetly add a remark in the Readme (or fix support for Python 3). Will leave this ticket open until this is done.

**Comment by ReneVolution** [comment]
Using Issue #13 for further Python 3 Support tracking.
