### ISSUE TITLE
prof_omemo_plugin.prof_on_message_stanza_receive(): return value undefined, expected boolean

### ISSUE THREAD

**Issue by Midar** [ReneVolution/profanity-omemo-plugin#11]
I get the above message as soon as I start profanity. I tried with the latest release of python-{axolotl,axoltl-curve25519,omemo} as well as git HEAD, no difference.

The actual error from profanity.log seems to be:
```
23/01/2017 21:33:16: prof: ERR: Plugin error - prof_omemo_plugin.prof_on_message_stanza_receive(): return value undefined, expected boolean
23/01/2017 21:33:16: stderr: ERR: Traceback (most recent call last):             
23/01/2017 21:33:16: stderr: ERR:   File "/Users/js/.local/share/profanity/plugins/prof_omemo_plugin.py", line 128, in func_wrapper
23/01/2017 21:33:16: stderr: ERR:     return func(*args, **kwargs)               
23/01/2017 21:33:16: stderr: ERR:   File "/Users/js/.local/share/profanity/plugins/prof_omemo_plugin.py", line 313, in prof_on_message_stanza_receive
23/01/2017 21:33:16: stderr: ERR:     _handle_devicelist_update(stanza)          
23/01/2017 21:33:16: stderr: ERR:   File "/Users/js/.local/share/profanity/plugins/prof_omemo_plugin.py", line 186, in _handle_devicelist_update
23/01/2017 21:33:16: stderr: ERR:     xmpp.update_devicelist(own_jid, sender_jid, msg_dict['devices'])
23/01/2017 21:33:16: stderr: ERR:   File "/opt/pkg/lib/python2.7/site-packages/profanity_omemo_plugin-0.0.1-py2.7.egg/profanity_omemo_plugin/xmpp.py", line 55, in update_devicelist
23/01/2017 21:33:16: stderr: ERR:     omemo_state = ProfOmemoState()             
23/01/2017 21:33:16: stderr: ERR:   File "/opt/pkg/lib/python2.7/site-packages/profanity_omemo_plugin-0.0.1-py2.7.egg/profanity_omemo_plugin/prof_omemo_state.py", line 58, in __new__
23/01/2017 21:33:16: stderr: ERR:     new_state = OmemoState(own_jid, connection, own_jid, DummyPLugin())
23/01/2017 21:33:16: stderr: ERR: TypeError: __init__() takes exactly 2 arguments (5 given)
```

**Comment by ReneVolution** [comment]
You seem to still have the wrong `python-omemo` package installed. Was this an update?
We had to switch to a different git and branch for future development which is respected in the setup.py, but apparently this does not work for the dependencies.

Please do a `pip uninstall python-omemo protobuf` before running `python setup.py install --force`

I included protobuf as the latest comes with incompabilities, but that is handled in the setup.py as well.

Let me know how it goes.

**Comment by ReneVolution** [comment]
Closing this as it id fixed. The sending issue is tracked in #12.

**Comment by Midar** [comment]
I'm not sure depending on an older version of these is a good idea. Why not update the code to work with the current versions? Other things will depend on the newer version and it is not possible to install both alongside. Also, at least protobuf is not installed via pip, but via package management.

**Comment by ReneVolution** [comment]
I don't understand what you mean.

`python-omemo` is used with it's latest up-to-date fork.
`protobuf` is not used in it's latest version because of missing shared libraries in the package.
