### ISSUE TITLE
can't send non-omemo messages

### ISSUE THREAD

**Issue by nwtti** [ReneVolution/profanity-omemo-plugin#12]
After installing the omemo and protobuf packages comming with your setup I'm getting the `Plugin error - prof_omemo_plugin.prof_on_iq_stanza_receive(): return value undefined, expected boolean` error on one account (jabber.at), but not on my second account (jabber.de). My stderr output is different than in #11.
Both accounts behave the same, ich can receive messages (omemo and unencrypted), but can only send omemo encrypted messages, even after `/omemo off` and starting a new chat.

```
24/01/2017 22:00:28: prof: ERR: Plugin error - prof_omemo_plugin.prof_on_iq_stanza_receive(): return value undefined, expected boolean
24/01/2017 22:00:28: stderr: ERR: Traceback (most recent call last):
24/01/2017 22:00:28: stderr: ERR:   File "/home/witti/.local/share/profanity/plugins/prof_omemo_plugin.py", line 128, in func_wrapper
24/01/2017 22:00:28: stderr: ERR:     return func(*args, **kwargs)
24/01/2017 22:00:28: stderr: ERR:   File "/home/witti/.local/share/profanity/plugins/prof_omemo_plugin.py", line 357, in prof_on_iq_stanza_receive
24/01/2017 22:00:28: stderr: ERR:     _handle_bundle_update(stanza)
24/01/2017 22:00:28: stderr: ERR:   File "/home/witti/.local/share/profanity/plugins/prof_omemo_plugin.py", line 205, in _handle_bundle_update
24/01/2017 22:00:28: stderr: ERR:     bundle_info = xmpp.unpack_bundle_info(stanza)
24/01/2017 22:00:28: stderr: ERR:   File "/usr/lib/python2.7/site-packages/profanity_omemo_plugin-0.0.1-py2.7.egg/profanity_omemo_plugin/xmpp.py", line 147, in unpack_bundle_info
24/01/2017 22:00:28: stderr: ERR:     device_id = items_node.attrib['node'].split(':')[-1]
24/01/2017 22:00:28: stderr: ERR: AttributeError: 'NoneType' object has no attribute 'attrib'
```

**Comment by ReneVolution** [comment]
Could you please provide the debug log? To do so please run `profanity -l DEBUG` and reproduce your issue. Thanks.

**Comment by nwtti** [comment]
I've createt a new Account for that, because I don't wanna leak infos about my contacts. The new account is on the same server as the one giving a error message, but on this one it doesn't give me that error.
Message sending behavior is the same, I can't send non encrypted messages as long as the plugin is loaded, it only works if I unload it. If its loaded and omemo is turned off, profanity doesn't react to message input.
I've played a bit around with these things as you can see in the log.

[profanity.log.txt](https://github.com/ReneVolution/profanity-omemo-plugin/files/730833/profanity.log.txt)

**Comment by ReneVolution** [comment]
It seems that you run into notification errors *when receiving OMEMO encrypted messages*, which may cause that the messages are not posted to the history.

Why do you think you can't *send unencrypted messages* ?

See:
```
25/01/2017 21:02:15: prof: ERR: Error sending desktop notification:
25/01/2017 21:02:15: prof: ERR:   -> Message : witti@jabber.de/Gajim (win 2)
25/01/2017 21:02:15: prof: ERR:   -> Error   : GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
```

Could you try with `/notify off` ?

**Comment by nwtti** [comment]
Well, I think i could do this but I reinstalled my operating system today and now im failing on installing this plugin again. This time I am having some sqlite errors when running `setup.py test`.

**Comment by ReneVolution** [comment]
What Python version? Traceback? Logfile? ;)

**Comment by nwtti** [comment]
Got it to work using python2, the behavior of not sending unencrypted messages when the plugin is enables is the same.

**Comment by ReneVolution** [comment]
Sorry, can't help without proper info here. The logs you provided do not match the error you describe. Closing this issue. Feel free to re-open it with proper info.

**Comment by BastiTee** [comment]
Hi there,
I am having the same issue with the error message in the log:
```
13/09/2017 13:35:45: prof: INF: ProfOmemoPlugin - Bundle update detected.
13/09/2017 13:35:45: prof: INF: ProfOmemoPlugin - Bundle Information received.
13/09/2017 13:35:45: prof: INF: ProfOmemoPlugin - Unwrapping bundle info.
13/09/2017 13:35:45: prof: ERR: Plugin error - prof_omemo_plugin.prof_on_iq_stanza_receive(): return value undefined, expected boolean
13/09/2017 13:35:45: stderr: ERR: Traceback (most recent call last):
13/09/2017 13:35:45: stderr: ERR:   File "/root/.local/share/profanity/plugins/prof_omemo_plugin.py", line 128, in func_wrapper
13/09/2017 13:35:45: stderr: ERR:     return func(*args, **kwargs)
13/09/2017 13:35:45: stderr: ERR:   File "/root/.local/share/profanity/plugins/prof_omemo_plugin.py", line 357, in prof_on_iq_stanza_receive
13/09/2017 13:35:45: stderr: ERR:     _handle_bundle_update(stanza)
13/09/2017 13:35:45: stderr: ERR:   File "/root/.local/share/profanity/plugins/prof_omemo_plugin.py", line 205, in _handle_bundle_update
13/09/2017 13:35:45: stderr: ERR:     bundle_info = xmpp.unpack_bundle_info(stanza)
13/09/2017 13:35:45: stderr: ERR:   File "/root/.local/lib/python2.7/site-packages/profanity_omemo_plugin-0.0.1-py2.7.egg/profanity_omemo_plugin/xmpp.py", line 149, in unpack_bundle_info
13/09/2017 13:35:45: stderr: ERR:     device_id = items_node.attrib['node'].split(':')[-1]
13/09/2017 13:35:45: stderr: ERR: AttributeError: 'NoneType' object has no attribute 'attrib'
```
I am using libmesode 0.9.1 profanity 0.5.1 and plugin 0.1.1. I have a docker container where this is reproducable at https://github.com/BastiTee/dockerfiles/blob/master/profanity-omemo/Dockerfile 

Glad if I can provide more info. Thanks!
