### ISSUE TITLE
cannot load plugin

### ISSUE THREAD

**Issue by mvhulten** [ReneVolution/profanity-omemo-plugin#17]
I run Debian stable but installed Profanity 0.5 from sid.

I installed the OMEMO plugin with success (`install.sh` results in exit code 0, and

        $ ls -l ~/.local/share/profanity/plugins/
    total 36
    -rw-r--r-- 1 marco staff 16907 Jan 28 13:13 prof_omemo_plugin.py
    -rw-r--r-- 1 marco marco 15681 Jan 28 13:14 prof_omemo_plugin.pyc
), but when I try to load the plugin, it says

    Failed to load plugin: prof_omemo_plugin.py

**Comment by strugee** [comment]
@mvhulten you need to provide more details. Logs, etc.

**Comment by mvhulten** [comment]
In the `profanity.log` I found this error:

    28/01/2017 23:38:24: prof: ERR: Plugin error - prof_omemo_plugin.prof_on_message_stanza_receive(): return value undefined, expected boolean

but it does not do that anymore, and I do not know what has changed.

When I now start Profanity, I first get normal info (`profanity.log`):

    28/01/2017 23:41:47: prof: INF: Starting Profanity (0.5.0)...
    28/01/2017 23:41:47: prof: INF: Initialising chat logs
    28/01/2017 23:41:47: prof: INF: Initialising groupchat logs
    28/01/2017 23:41:47: prof: INF: Loading accounts
    28/01/2017 23:41:47: prof: INF: Initialising UI
    28/01/2017 23:41:47: prof: INF: Initialising XMPP
    28/01/2017 23:41:47: prof: INF: Loading capabilities cache
    28/01/2017 23:41:47: prof: INF: Initialising commands
    28/01/2017 23:41:47: prof: INF: Initialising contact list
    28/01/2017 23:41:47: prof: INF: Loading TLS certificates
    28/01/2017 23:41:47: prof: INF: Initialising OTR
    28/01/2017 23:41:48: prof: INF: Loaded plugin: prof_omemo_plugin.py
    28/01/2017 23:41:48: prof: INF: ProfOmemoPlugin - prof_init() called
    28/01/2017 23:41:48: prof: WRN: ProfOmemoPlugin - No User logged in on plugin.prof_init()
    28/01/2017 23:41:48: prof: INF: Starting main event loop

Good, OMEMO *does* load.  Then I `/connect` to my jabber account and then the log file hogs up with lots of repeated ProfOmemoPlugin messages about added devices to my jabber account.  After a minute or so Profanity is unresponsive and I have to kill it.

At other times, it doesn't crash, and when I then start a chat with `/msg handle` and then `/omemo on`, at the top next to the handle of the person I'm chatting to it still says "unencrypted", even though I know that she is using OMEMO (on Conversations).  It is also clear that on her device the messages are not encrypted even though the encryption lock is closed.

So, the plugin does appear to load now, but it does not work in my case.

**Comment by ReneVolution** [comment]
> Good, OMEMO does load. Then I /connect to my jabber account and then the log file hogs up with lots of repeated ProfOmemoPlugin messages about added devices to my jabber account. After a minute or so Profanity is unresponsive and I have to kill it.

How many contacts do you have that use OMEMO as well? I just wonder if run into a bottleneck here.

> At other times, it doesn't crash, and when I then start a chat with /msg handle and then /omemo on...

You need to `/omemo start contact-jid` to initialise OMEMO from your end. `/omemo [on|off]` is used to turn the plugin on or off on a global level.

> at the top next to the handle of the person I'm chatting to it still says "unencrypted", even though I...

The visualisation that you use OMEMO has still to come with an plugin update which tough will require you to have profanity >= v0.5.1 installed.

**Comment by ReneVolution** [comment]
Hey @mvhulten,

just fixed a bug which could relate to the issues you had.
Could you try with the current plugin master and profanity >= v0.5.1 ?

**Comment by mvhulten** [comment]
On my usual systems, OpenBSD and Debian, Profanity 0.5.0 is the newest available.  But Profanity 0.5.1 is available on Android / F-Droid through Termux / apt.  For later reference, I document the following procedure.

I ran these commands on an Android-based system (Fairphone Open 16.12.0).  I updated Termux and its packages, and installed Profanity 0.5.1, amongst other things needed to use OMEMO:

    apt install profanity git clang libffi-dev openssl-dev
    git clone https://github.com/ReneVolution/profanity-omemo-plugin.git
    cd profanity-omemo-plugin/
    export CONFIG_SHELL="$PREFIX/bin/sh"
    bash install.sh
    profanity

I needed to set `CONFIG_SHELL` and invoke `install.sh` through bash, as `/usr/` is not accessible (apparently Android is not POSIX compliant).  In profanity I enable the OMEMO plugin.  I get the `prof_omemo_plugin.prof_on_message_stanza_receive(): return value undefined, expected boolean` error message again.  Then I start a conversation.

    /plugins load prof_omemo_plugin.py
    /omemo start jid
    /msg jid

Now it does say in the bar at the top that it is using OMEMO.

When I send a message to my own jid, it does not arrive at other clients.  As soon as one of my two OMEMO contacts gets online, I will do further testing.

**Comment by mvhulten** [comment]
When sending unencrypted messages to one of the contacts, they arrive (unencrypted).

When I try to send an OMEMO-encrypted message to either of my two contacts, they do not arrive.  At least one of my two contacts can only send unencrypted messages to me.

I am using Profanity-OMEMO; my contacts are using Conversations.

**Comment by ReneVolution** [comment]
That's odd. I have been chatting the whole day today with a friend using OMEMO myself and Gajim/Conversations.im on the other side. Please give me at least some breadcrumbs (in form of a traceback from the logs).

**Comment by mvhulten** [comment]
I will get back with more info this weekend.

**Comment by ReneVolution** [comment]
@mvhulten Any news on this?

**Comment by mvhulten** [comment]
Sorry, no time right now.
Maybe close it since the issue is different anyway from the original.

**Comment by ReneVolution** [comment]
Sure thing. Please feel free to create a new issue whenever you've time.
