### ISSUE TITLE
Can't load prof_omemo_plugin.py

### ISSUE THREAD

**Issue by vestingz** [ReneVolution/profanity-omemo-plugin#19]
install.sh seems to install the plugin successfully to ~/.local/share/profanity/plugins, but /plugins load prof_omemo_plugin.py fails.
Here's a paste from profanity.log: http://pastebin.com/raw/ESArnvdv

**Comment by ReneVolution** [comment]
This looks very much like some file permissions on your system are somehow messed up.

**Comment by vestingz** [comment]
True. I sorted this out and now i'm getting following error:
`03/02/2017 18:51:44: stderr: ERR:   File "/home/<user>/.local/share/profanity/plugins/prof_omemo_plugin.py", line 29, in <module>
03/02/2017 18:51:44: stderr: ERR:     import profanity_omemo_plugin.xmpp as xmpp
03/02/2017 18:51:44: stderr: ERR: ImportError: No module named profanity_omemo_plugin.xmpp`

**Comment by ReneVolution** [comment]
Hmm ... looks like you may have multiple Python versions installed on your system. You might need to run the `./install.sh` with `sudo` privileges.

**Comment by ReneVolution** [comment]
My dear friend @bascht pointed out that using `sudo` is bad and that there is an alternative with using `python setup.py install --user`.

So, **DO NOT USE SUDO** ☠️
