### ISSUE TITLE
Failed to load plugin: prof_omemo_plugin.py

### ISSUE THREAD

**Issue by goblin** [ReneVolution/profanity-omemo-plugin#20]
I'm on Profanity 0.5.1, Python 3.5.2, this plugin at the v0.1.1 tag. I've ran `python setup.py install --force` manually as root (because the user didn't have permission to write to /usr) and then the `cp deploy/prof_omemo_plugin.py ~/.local/share/profanity/plugins/` manually as the user.

After trying to load the plugin, this is all I see in logs:
```
05/02/2017 23:19:31: prof: DBG: Input received: /plugins load prof_omemo_plugin.py
05/02/2017 23:19:31: prof: DBG: Initialised prof module
05/02/2017 23:19:31: prof: INF: Failed to load plugin: prof_omemo_plugin.py

```

**Comment by ReneVolution** [comment]
Can you please try the plugin in current master and see if it fixes anything? Looks like an issue with Python 3 to me.

**Comment by goblin** [comment]
Current master against Profanity 0.5.1 results in the same error.

I'm currently having issues compiling Profanity master (`configure.ac:87: error: possibly undefined macro: AC_MSG_ERROR`)

**Comment by goblin** [comment]
Here's the error when trying to run omemo master with Profanity 0.5.1 compiled with **python 2.7.12**:

```
06/02/2017 12:21:23: prof: INF: Failed to load plugin: prof_omemo_plugin.py
06/02/2017 12:21:23: stderr: ERR: Traceback (most recent call last):
06/02/2017 12:21:23: stderr: ERR:   File "/home/goblin/.local/share/profanity/plugins/prof_omemo_plugin.py", line 29, in <module>
06/02/2017 12:21:23: stderr: ERR:     import profanity_omemo_plugin.xmpp as xmpp
06/02/2017 12:21:23: stderr: ERR: ImportError: No module named profanity_omemo_plugin.xmpp

```

And omemo v0.1.1:

```
06/02/2017 12:23:20: stderr: ERR: Traceback (most recent call last):
06/02/2017 12:23:20: stderr: ERR:   File "/home/goblin/.local/share/profanity/plugins/prof_omemo_plugin.py", line 26, in <module>
06/02/2017 12:23:20: stderr: ERR:     import profanity_omemo_plugin.xmpp as xmpp
06/02/2017 12:23:20: stderr: ERR: ImportError: No module named profanity_omemo_plugin.xmpp

```

**Comment by goblin** [comment]
Right, yeah, it works OK with Python 2.7.12, so your guess was right :-) Thanks

**Comment by ReneVolution** [comment]
Ok, great. I guess the ticket can be closed then. Feel free to reopen if not.
