### ISSUE TITLE
Plugin error - prof_omemo_plugin.prof_on_message_stanza_send(): return value undefined, expected string, unicode or None

### ISSUE THREAD

**Issue by blizzz** [ReneVolution/profanity-omemo-plugin#21]
I run 0.5.1-1

I installed the module as described on the Readme.

loading the module and starting it succeeds, however when writing messages the error message ``Plugin error - prof_omemo_plugin.prof_on_message_stanza_send(): return value undefined, expected string, unicode or None`` is just thrown. Nothing arrives at the recipient.

**Comment by ReneVolution** [comment]
Could you check the logs for more information?

**Comment by blizzz** [comment]
yup, with debug level:

```
06/04/2017 11:13:05: xmpp: DBG: RECV: <iq id="prof_ping_24" to="ME@SERVER.TLD/profanity" type="result"/>
06/04/2017 11:13:05: prof: DBG: iq stanza handler fired
06/04/2017 11:13:05: prof: INF: ProfOmemoPlugin - Received IQ: <iq id="prof_ping_24" to="ME@SERVER.TLD/profanity" type="result"/>
06/04/2017 11:13:05: prof: DBG: Autoping: Pong handler fired: prof_ping_24.
06/04/2017 11:13:09: prof: DBG: Input received: test omemo 2
06/04/2017 11:13:09: prof: INF: Active Chats: [PEER@SERVER.TLD]
06/04/2017 11:13:09: prof: INF: ProfOmemoPlugin - Using database path /home/USER/.local/share/profanity/omemo/ME_at_SERVER.TLD/omemo.db
06/04/2017 11:13:09: prof: ERR: Plugin error - prof_omemo_plugin.prof_pre_chat_message_send(): return value undefined, expected string, unicode or None
```

**Comment by momonosuke** [comment]
I'm usign GNU Parabola / linux-libre and I'm getting the same error. I installed with
$ sudo pacman -S python-cryptography and later clone the git.

I can't send messages ( it loses) but I can receive.

**Comment by ReneVolution** [comment]
Looks like I have to include more logging first. I hope to find some time soon to do it.

**Comment by Fraterius** [comment]
I've just installed profanity with omemo plugin on pretty recent archlinux and got the same problem. Logs aren't saying much just like above one. If there's any feedback needed please let me know.

**Comment by flocke** [comment]
Got a very similar error with profanity 0.5.1 on Exherbo Linux:
```
08:59:51 - Plugin error - prof_omemo_plugin.prof_on_message_stanza_receive(): return value undefined, expected boolean
08:59:51 - Plugin error - prof_omemo_plugin.prof_on_message_stanza_receive(): return value undefined, expected boolean
```
Tested with Python 2.7.13 and Python 3.6.1 both with the OMEMO plugin version 0.1.1 and the current GIT head.

**Comment by flocke** [comment]
From what I can get from the log file it happens when profanity receives a device list update (from Conversations).
Once better logging is implemented I will try to find more information, right now even in the DEBUG log level no additional relevant information are shown.

**Comment by ReneVolution** [comment]
Hey @flocke,

could you please check again with current HEAD and see if there is now more info coming to the logs?

**Comment by flocke** [comment]
@ReneVolution It seems to be working with the current HEAD, at least the error on start message is gone (using profanity HEAD, OMEMO HEAD and python 3.6.1).
I will start and try to do some messaging with OMEMO enabled and look out for some bugs.

**Comment by ReneVolution** [comment]
@flocke That is even better news 😺 

Btw: You don't need the python-omemo package anymore, as the plugin ships it directly for easier maintenance.

**Comment by ReneVolution** [comment]
Closing the issue now. Feel free to reopen if necessary.
