### ISSUE TITLE
Could not decrypt Messages. ValueError: Authentication tag must be 16 bytes or longer.

### ISSUE THREAD

**Issue by ReneVolution** [ReneVolution/profanity-omemo-plugin#22]
The plugin fails when trying to encrypt messages from Conversations.im.

Example Message:

`<message id="bb4d3e07-a0f7-43d8-89be-6bbdde8b12cf" to="renevolution@yakshed.org" type="chat" from="bob@cryp.to/phone"><encrypted xmlns="eu.siacs.conversations.axolotl"><header sid="2032384913"><key rid="584672103" prekey="true">MwiKoQESIQWk2IATiPLrhz5vcq4DHAtQAqXR9wLc+VuXL0Sev+mBdRohBdrhazhjnm7gvRXcoW8JSzJ9vzmsYPFwXdkWQk9z/ftVImIzCiEFbbXlfruNVyIJqa3wHR12D8ZWAyhkLTDdvNoAyhtHQCUQdxgAIjCKrIeyEI4Wic+V3P+suZJoaJgZ3W+gOSLX09uBz5kNJa0Ao/IRQZHMNPxyN     essa+OwDO5o/CNiTyiR947JBzDQAQ==</key><key  id="98220780">MwohBWW46btPjaFWApkw+mmR4i5/IUUpVq1SmNaIIuG3SCMxEAAYAiIwquoHGjaGKE3ufpErSTUJ6efV4yoUqO6uxsvTbxDaeVZjlNbw98QMgyBZ9YwRBSG4KVGmHW9+vxE=</key><key rid="2020522673" prekey="true">Mwje3NoFEiEFwzhjGUKuTn7ZrDLAGEtNLN0PXsJzGMGZdqeGRJBbaTkaIQXa4Ws4Y55u4L0V3KFvCUsyfb85rGDxcF3ZFkJPc/37VSJiMwohBRiizIUM7dO7wNZsnpnu6YeX4GmjqSVAmJMeDYEfZQ9cEFkYACI w2c7pzltiNu4JgkhTDaWCPPlYtVW8kzUZiAEaEc2R38b/WZJ4Y4sJfPENElQ3IJ1JZhqdA/Qx+RookfeOyQcwvcQD</key><iv>B8PgnqFfx86jveS9xXEawQ==</iv></header><payload>ZxVKwzE=</payload></encrypted><markable xmlns="urn:xmpp:chat-markers:0"/><origin-id id="bb4d3e07-a0f7-43d8-89be-6b     bdde8b12cf" xmlns="urn:xmpp:sid:0"/><store xmlns="urn:xmpp:hints"/><encryption namespace="eu.siacs.conversations.axolotl" xmlns="urn:xmpp:eme:0" name="OMEMO"/></message>`

It seems the issue comes up since the new prekey handling in Conversations.

**Comment by iNPUTmice** [comment]
This is described here: https://github.com/ChatSecure/ChatSecure-iOS/issues/647

You should be able to pull the changes from the gajim omemo library.

**Comment by ReneVolution** [comment]
Thanks @iNPUTmice. Good catch. Current Master can talk to Conversations.im again.
