### ISSUE TITLE
With two OMEMO enabled devices on the same account, profanity freezes

### ISSUE THREAD

**Issue by jdkbx** [ReneVolution/profanity-omemo-plugin#23]
I just started to use profanity as mcabber is missing omemo support. I have conversations running on an android device using the same account. When I start profanity the log quickly fills with

`15/06/2017 10:26:31: prof: DBG: Message stanza handler fired`
`15/06/2017 10:26:31: prof: INF: ProfOmemoPlugin - Received Message: <message to="jdkbx@SERVER/profanity" type="headline" from="jdkbx@SERVER"><event xmlns="http://jabber.org/protocol/pubsub#event"><items node="eu.siacs.conversations.axolotl.devicelist"><item id="1"><list xmlns="eu.siacs.conversations.axolotl"><device id="864301418"/></list></item></items></event></message>`
`15/06/2017 10:26:31: prof: INF: ProfOmemoPlugin - Device List update detected.`
`15/06/2017 10:26:31: prof: INF: ProfOmemoPlugin - Received devicelist update from jdkbx@SERVER`
`15/06/2017 10:26:31: prof: INF: ProfOmemoPlugin - Announce own device list.`
`15/06/2017 10:26:31: prof: INF: ProfOmemoPlugin - <iq type="set" from="jdkbx@SERVER/profanity" id="a64eae3c-d6aa-4070-94f7-f14c2e752a00"><pubsub xmlns="http://jabber.org/protocol/pubsub"><publish node="eu.siacs.conversations.axolotl.devicelist"><item id="1"><list xmlns="eu.siacs.conversations.axolotl"><device id="864301418"/></list></item></publish></pubsub></iq>`
`15/06/2017 10:26:31: conn: DBG: SENT: <iq type="set" from="jdkbx@SERVER/profanity" id="a64eae3c-d6aa-4070-94f7-f14c2e752a00"><pubsub xmlns="http://jabber.org/protocol/pubsub"><publish node="eu.siacs.conversations.axolotl.devicelist"><item id="1"><list xmlns="eu.siacs.conversations.axolotl"><device id="864301418"/></list></item></publish></pubsub></iq>`
`15/06/2017 10:26:31: prof: INF: ProfOmemoPlugin - Adding jdkbx@SERVER to the completer.`
`15/06/2017 10:26:31: prof: DBG: Autocomplete add /omemo start for prof_omemo_plugin.py`
`15/06/2017 10:26:31: prof: DBG: Autocomplete add /omemo show_devices for prof_omemo_plugin.py`
`15/06/2017 10:26:31: prof: DBG: Autocomplete add /omemo reset_devicelist for prof_omemo_plugin.py`
`15/06/2017 10:26:31: xmpp: DBG: RECV: <iq id="ed3ed6ee-63e6-46ec-8af8-03bd2f08e5ba" to="jdkbx@SERVER/profanity" type="result"/>`
`15/06/2017 10:26:31: prof: DBG: iq stanza handler fired`
`15/06/2017 10:26:31: prof: INF: ProfOmemoPlugin - Received IQ: <iq id="ed3ed6ee-63e6-46ec-8af8-03bd2f08e5ba" to="jdkbx@SERVER/profanity" type="result"/>`
`15/06/2017 10:26:31: xmpp: DBG: RECV: <message to="jdkbx@SERVER/profanity" type="headline" from="jdkbx@SERVER"><event xmlns="http://jabber.org/protocol/pubsub#event"><items node="eu.siacs.conversations.axolotl.devicelist"><item id="1"><list xmlns="eu.siacs.conversations.axolotl"><device id="864301418"/></list></item></items></event></message>`

These messages are repeated a few hundred lines a second. All with different iq ids.
After around two minutes profanity is just frozen, not reacting to anything. When I log off with the Android device, profanity keeps running as expected, and the logfile settles. When I log on again the same freeze can be triggered reliably. I assume some buffer is filled up.
With the omemo plugin disabled (/omemo off) profanity works fine.

**Comment by bascht** [comment]
Huh. This pretty much exactly looks like the issue I was encountering the last few weeks. 
Thanks for tracing it down! :+1: I'm happy to help debugging.

**Comment by ReneVolution** [comment]
Thanks a lot for tracking it down @jdkbx. Will look at it as soon as possible.
It looks like an infinite loop in the device list management with own devices.

**Comment by ReneVolution** [comment]
Hmm ... i wasn't able to reproduce this issue yet.
What bugs me a little, is that there is only a single device id mentioned in the device list updates. I would at least expect different device id's. Will need to dig deeper here.

**Comment by ReneVolution** [comment]
@bascht @jdkbx: Could you create a longer log (e.g. from application start to 3 repetitions of the devicelist updates)?

**Comment by jdkbx** [comment]
https://gist.github.com/jdkbx/6912f4ef7463cd8b69f56a2c6886249e

**Comment by ReneVolution** [comment]
Can you please test again with the current master?

**Comment by jdkbx** [comment]
Looks good. Profanity keeps running. Thank you very much.

**Comment by ReneVolution** [comment]
Awesome ... thanks for reporting and help to fix this.
