### ISSUE TITLE
A correct support of OMEMO: 12 byte for initilization vector (IV)

### ISSUE THREAD

**Issue by Neustradamus** [ReneVolution/profanity-omemo-plugin#56]
There is a problem in the code:
- https://github.com/xsf/xeps/pull/894

**Comment by licaon-kter** [comment]
Why? Is this still maintained since upstream already got OMEMO?

**Comment by ReneVolution** [comment]
This plugin is no longer maintained. As @licaon-kter pointed out, there is now upstream support for OMEMO which makes this plugin redundant.

**Comment by SamWhited** [comment]
Please consider archiving this project on GitHub to make this obvious; thanks!

**Comment by ReneVolution** [comment]
While the Readme already contains a note/badge about this, I agree it would be more obvious when archived. Will do so we once I am close to a desktop. Couldn’t do it from mobile.
